name: data-miner-umg
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8.10
    - pandas=1.3.1
    - pip=21.2.2
    - scrapy=2.4.1
    - scikit-learn=1.1.3
    - nltk=3.7
    - kneed=0.7.0
